version: '3.8'
services:
  api:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: